.\Lab2\Task1\src\one.py
.\Lab2\Task2\src\two.py
.\Lab2\Task3\src\three.py
.\Lab2\Task4\src\four.py
.\Lab2\Task5\src\five.py
.\Lab2\Task7\src\seven.py
.\Lab3\Task1\src\task_qs.py
.\Lab3\Task2\src\task_anti_qs.py
.\Lab3\Task3\src\task_scarecrow.py
.\Lab3\Task5\src\task_h_index.py
.\Lab3\Task6\src\task_sum.py
.\Lab3\Task7\src\task_digital_sort.py
.\Lab4\Task2\src\task_queue.py
.\Lab4\Task3\src\task_bracket_sequence.py
.\Lab4\Task5\src\task_max_stack.py
.\Lab4\Task7\src\task_max_in_sequence.py
.\Lab4\Task8\src\task_postfix.py
.\Lab4\Task13\src\task_stack_and_queue.py